import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1769381656317 implements MigrationInterface {
    name = 'InitialSchema1769381656317'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "bio" text, "interests" text NOT NULL DEFAULT '', "skills" text NOT NULL DEFAULT '', "educationLevel" character varying, "careerGoals" text NOT NULL DEFAULT '', "hobbies" text NOT NULL DEFAULT '', "location" character varying, "timezone" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_8481388d6325e752cd4d7e26c6" UNIQUE ("userId"), CONSTRAINT "PK_1ec6662219f4605723f1e41b6cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."guardianship_links_relationship_enum" AS ENUM('parent', 'legal_guardian', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."guardianship_links_status_enum" AS ENUM('pending', 'active', 'revoked')`);
        await queryRunner.query(`CREATE TABLE "guardianship_links" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "guardianId" uuid, "minorId" uuid NOT NULL, "relationship" "public"."guardianship_links_relationship_enum" NOT NULL DEFAULT 'parent', "status" "public"."guardianship_links_status_enum" NOT NULL DEFAULT 'pending', "consentGivenAt" TIMESTAMP, "invitationToken" character varying, "invitationExpiresAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4e9d1c25192edf4acdb54e51e5a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."interest_signals_source_enum" AS ENUM('google', 'spotify', 'youtube', 'discord', 'instagram', 'twitter', 'upload', 'manual')`);
        await queryRunner.query(`CREATE TYPE "public"."interest_signals_entitytype_enum" AS ENUM('topic', 'person', 'organization', 'place', 'event', 'media', 'product', 'skill', 'career', 'hobby')`);
        await queryRunner.query(`CREATE TABLE "interest_signals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "source" "public"."interest_signals_source_enum" NOT NULL, "connectorId" uuid, "sourceId" character varying, "timestamp" TIMESTAMP NOT NULL, "topic" character varying NOT NULL, "entity" character varying, "entityType" "public"."interest_signals_entitytype_enum", "weight" double precision NOT NULL DEFAULT '1', "confidence" double precision NOT NULL DEFAULT '1', "rawMetadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_06091e7ead8168499e7abbbcb5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b2e053d53aafa4ea01c929b1c3" ON "interest_signals" ("userId", "source", "topic") `);
        await queryRunner.query(`CREATE TYPE "public"."connectors_type_enum" AS ENUM('google', 'spotify', 'youtube', 'discord', 'instagram', 'twitter', 'upload', 'manual')`);
        await queryRunner.query(`CREATE TYPE "public"."connectors_status_enum" AS ENUM('pending', 'active', 'expired', 'error', 'disconnected')`);
        await queryRunner.query(`CREATE TABLE "connectors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" "public"."connectors_type_enum" NOT NULL, "status" "public"."connectors_status_enum" NOT NULL DEFAULT 'pending', "accessToken" text, "refreshToken" text, "tokenExpiresAt" TIMESTAMP, "scopes" text NOT NULL DEFAULT '', "lastSyncAt" TIMESTAMP, "metadata" jsonb, "errorMessage" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1334e2a68a8de86d1732a8e3fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."resources_type_enum" AS ENUM('article', 'video', 'course', 'book', 'tool', 'community', 'mentor', 'event', 'other')`);
        await queryRunner.query(`CREATE TABLE "resources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "milestoneId" uuid NOT NULL, "type" "public"."resources_type_enum" NOT NULL DEFAULT 'other', "title" character varying NOT NULL, "url" character varying, "description" text, "isFree" boolean NOT NULL DEFAULT true, "estimatedTime" character varying, "provider" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_632484ab9dff41bba94f9b7c85e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."milestones_status_enum" AS ENUM('pending', 'in_progress', 'completed', 'skipped')`);
        await queryRunner.query(`CREATE TYPE "public"."milestones_verificationmethod_enum" AS ENUM('self_report', 'guardian_approval', 'certificate', 'quiz', 'project', 'external')`);
        await queryRunner.query(`CREATE TABLE "milestones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roadmapId" uuid NOT NULL, "title" character varying NOT NULL, "description" text, "order" integer NOT NULL DEFAULT '0', "status" "public"."milestones_status_enum" NOT NULL DEFAULT 'pending', "dueDate" date, "completedAt" TIMESTAMP, "tokenReward" integer, "verificationRequired" boolean NOT NULL DEFAULT false, "verificationMethod" "public"."milestones_verificationmethod_enum", "estimatedDuration" character varying, "skills" text NOT NULL DEFAULT '', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0bdbfe399c777a6a8520ff902d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."roadmaps_status_enum" AS ENUM('draft', 'active', 'completed', 'archived')`);
        await queryRunner.query(`CREATE TABLE "roadmaps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "goalId" uuid NOT NULL, "title" character varying NOT NULL, "description" text, "estimatedDuration" character varying, "aiGenerated" boolean NOT NULL DEFAULT false, "aiModelUsed" character varying, "status" "public"."roadmaps_status_enum" NOT NULL DEFAULT 'draft', "startDate" date, "completedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9b0d527f9c64d15405c21e7ca54" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."goals_category_enum" AS ENUM('education', 'career', 'skill', 'health', 'financial', 'personal', 'social', 'creative', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."goals_status_enum" AS ENUM('draft', 'active', 'in_progress', 'completed', 'paused', 'abandoned')`);
        await queryRunner.query(`CREATE TABLE "goals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "title" character varying NOT NULL, "description" text, "category" "public"."goals_category_enum" NOT NULL DEFAULT 'other', "targetDate" date, "status" "public"."goals_status_enum" NOT NULL DEFAULT 'draft', "priority" integer NOT NULL DEFAULT '0', "parentGoalId" uuid, "tags" text NOT NULL DEFAULT '', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_26e17b251afab35580dff769223" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "token_balances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "availableBalance" numeric(20,8) NOT NULL DEFAULT '0', "lockedBalance" numeric(20,8) NOT NULL DEFAULT '0', "pendingBalance" numeric(20,8) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a9f4195c452704e9fe3064197aa" UNIQUE ("userId"), CONSTRAINT "REL_a9f4195c452704e9fe3064197a" UNIQUE ("userId"), CONSTRAINT "PK_e12dc361a93cf25efa25d0a4cdc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "passwordHash" character varying, "displayName" character varying NOT NULL, "avatarUrl" character varying, "dateOfBirth" date, "isMinor" boolean NOT NULL DEFAULT false, "privyDid" character varying, "walletAddress" character varying, "emailVerified" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "token_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tokenName" character varying NOT NULL DEFAULT 'Vision Token', "tokenSymbol" character varying NOT NULL DEFAULT 'VSN', "contractAddress" character varying, "chainId" integer, "chainName" character varying, "decimals" integer NOT NULL DEFAULT '18', "minorLockEnabled" boolean NOT NULL DEFAULT true, "defaultLockDurationDays" integer NOT NULL DEFAULT '365', "onChainEnabled" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fb9ed9c378212930a0c9c1a2cdb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."token_lock_status_lockreason_enum" AS ENUM('minor_protection', 'vesting', 'staking', 'guardian_requested')`);
        await queryRunner.query(`CREATE TABLE "token_lock_status" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "isLocked" boolean NOT NULL DEFAULT false, "lockedAmount" numeric(20,8) NOT NULL DEFAULT '0', "lockReason" "public"."token_lock_status_lockreason_enum" NOT NULL DEFAULT 'minor_protection', "lockStartDate" TIMESTAMP NOT NULL, "unlockDate" TIMESTAMP NOT NULL, "guardianApprovedEarlyUnlock" boolean NOT NULL DEFAULT false, "guardianId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_91f2f47fd80392caec2191026f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."token_ledger_entries_type_enum" AS ENUM('earn', 'spend', 'transfer_in', 'transfer_out', 'lock', 'unlock', 'mint', 'burn')`);
        await queryRunner.query(`CREATE TYPE "public"."token_ledger_entries_referencetype_enum" AS ENUM('milestone', 'sponsorship', 'reward', 'purchase', 'withdrawal', 'deposit')`);
        await queryRunner.query(`CREATE TABLE "token_ledger_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" "public"."token_ledger_entries_type_enum" NOT NULL, "amount" numeric(20,8) NOT NULL, "balanceBefore" numeric(20,8) NOT NULL, "balanceAfter" numeric(20,8) NOT NULL, "lockedBalanceBefore" numeric(20,8) NOT NULL DEFAULT '0', "lockedBalanceAfter" numeric(20,8) NOT NULL DEFAULT '0', "referenceType" "public"."token_ledger_entries_referencetype_enum", "referenceId" character varying, "description" character varying NOT NULL, "txHash" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a37308378a149d987954e916d37" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ed128f7dc3b032587678927664" ON "token_ledger_entries" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."subscription_entitlements_status_enum" AS ENUM('active', 'past_due', 'cancelled', 'incomplete', 'trialing')`);
        await queryRunner.query(`CREATE TABLE "subscription_entitlements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "planId" character varying NOT NULL, "planName" character varying NOT NULL, "features" jsonb NOT NULL DEFAULT '[]', "status" "public"."subscription_entitlements_status_enum" NOT NULL DEFAULT 'active', "stripeSubscriptionId" character varying, "currentPeriodStart" TIMESTAMP NOT NULL, "currentPeriodEnd" TIMESTAMP NOT NULL, "cancelAtPeriodEnd" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b3d4ec58e764e58b90c02770d43" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sponsors_type_enum" AS ENUM('individual', 'family', 'organization', 'corporate')`);
        await queryRunner.query(`CREATE TYPE "public"."sponsors_status_enum" AS ENUM('pending', 'active', 'paused', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "sponsors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "organizationName" character varying, "type" "public"."sponsors_type_enum" NOT NULL DEFAULT 'individual', "status" "public"."sponsors_status_enum" NOT NULL DEFAULT 'pending', "stripeCustomerId" character varying, "stripeSubscriptionId" character varying, "totalContributed" numeric(12,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6d1114fe7e65855154351b66bfc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sponsorships_type_enum" AS ENUM('monthly', 'one_time', 'milestone_based', 'goal_based')`);
        await queryRunner.query(`CREATE TYPE "public"."sponsorships_status_enum" AS ENUM('pending', 'active', 'paused', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "sponsorships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sponsorId" uuid NOT NULL, "beneficiaryId" uuid NOT NULL, "type" "public"."sponsorships_type_enum" NOT NULL DEFAULT 'one_time', "status" "public"."sponsorships_status_enum" NOT NULL DEFAULT 'pending', "monthlyAmount" numeric(12,2), "totalPledged" numeric(12,2), "totalDistributed" numeric(12,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'usd', "startDate" date NOT NULL, "endDate" date, "goalId" uuid, "milestoneRewards" jsonb NOT NULL DEFAULT '[]', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_393571b62d6dd0f63c6d3eb154b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sponsorship_ledger_entries_type_enum" AS ENUM('contribution', 'subscription_payment', 'refund', 'allocation', 'payout')`);
        await queryRunner.query(`CREATE TYPE "public"."sponsorship_ledger_entries_status_enum" AS ENUM('pending', 'processing', 'succeeded', 'failed', 'refunded', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "sponsorship_ledger_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sponsorId" uuid NOT NULL, "beneficiaryId" uuid, "type" "public"."sponsorship_ledger_entries_type_enum" NOT NULL, "amount" numeric(12,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'usd', "stripePaymentIntentId" character varying, "stripeChargeId" character varying, "status" "public"."sponsorship_ledger_entries_status_enum" NOT NULL DEFAULT 'pending', "description" character varying NOT NULL, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_aa7c2de3af0c2295b5021aa6f62" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_05b878bab57cd765e539ec5982" ON "sponsorship_ledger_entries" ("sponsorId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."recommendations_type_enum" AS ENUM('activity', 'event', 'course', 'career', 'school', 'community', 'content', 'opportunity')`);
        await queryRunner.query(`CREATE TYPE "public"."recommendations_category_enum" AS ENUM('education', 'career', 'hobby', 'social', 'health', 'entertainment', 'volunteer', 'skill_building')`);
        await queryRunner.query(`CREATE TYPE "public"."recommendations_source_enum" AS ENUM('ai_generated', 'curated', 'sponsor', 'community', 'partner')`);
        await queryRunner.query(`CREATE TYPE "public"."recommendations_status_enum" AS ENUM('active', 'viewed', 'saved', 'dismissed', 'expired')`);
        await queryRunner.query(`CREATE TABLE "recommendations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" "public"."recommendations_type_enum" NOT NULL, "category" "public"."recommendations_category_enum" NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "relevanceScore" double precision NOT NULL DEFAULT '0', "reasoning" text, "source" "public"."recommendations_source_enum" NOT NULL DEFAULT 'ai_generated', "externalId" character varying, "externalUrl" character varying, "imageUrl" character varying, "metadata" jsonb, "location" jsonb, "dateInfo" jsonb, "pricing" jsonb, "status" "public"."recommendations_status_enum" NOT NULL DEFAULT 'active', "userFeedback" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_23a8d2db26db8cabb6ae9d6cd87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "favorites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "recommendationId" uuid NOT NULL, "notes" text, "tags" text NOT NULL DEFAULT '', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3e26de10259d5e2d800f941aeae" UNIQUE ("userId", "recommendationId"), CONSTRAINT "PK_890818d27523748dd36a4d1bdc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "consent_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "connectorType" character varying NOT NULL, "scopes" text NOT NULL, "dataCategories" text NOT NULL, "consentGivenAt" TIMESTAMP NOT NULL, "expiresAt" TIMESTAMP, "revokedAt" TIMESTAMP, "guardianApprovalRequired" boolean NOT NULL DEFAULT false, "guardianApprovedAt" TIMESTAMP, "guardianId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_030be152eaa44998166470b2ccc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "user_profiles" ADD CONSTRAINT "FK_8481388d6325e752cd4d7e26c6d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guardianship_links" ADD CONSTRAINT "FK_1f6276d2420789d3800d8cde347" FOREIGN KEY ("guardianId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guardianship_links" ADD CONSTRAINT "FK_2e689397cdda619d53734a94853" FOREIGN KEY ("minorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interest_signals" ADD CONSTRAINT "FK_ab1b51d46b9d2bd40ce08ee876f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interest_signals" ADD CONSTRAINT "FK_3b90bf0281c016550b1b0ad518f" FOREIGN KEY ("connectorId") REFERENCES "connectors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "connectors" ADD CONSTRAINT "FK_d9f4add3509272c1aec440c3d45" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resources" ADD CONSTRAINT "FK_a9bd86651b6a4e30c5e2e9f235c" FOREIGN KEY ("milestoneId") REFERENCES "milestones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "milestones" ADD CONSTRAINT "FK_17e022d167f4860adfaf3332326" FOREIGN KEY ("roadmapId") REFERENCES "roadmaps"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roadmaps" ADD CONSTRAINT "FK_29f718c5a5cb41f2266d21ba207" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roadmaps" ADD CONSTRAINT "FK_4ecf772a639c37f4b05b8a07cbb" FOREIGN KEY ("goalId") REFERENCES "goals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "FK_57dd8a3fc26eb760d076bf8840e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "FK_45db60741e56aa6941b7cf77fde" FOREIGN KEY ("parentGoalId") REFERENCES "goals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "token_balances" ADD CONSTRAINT "FK_a9f4195c452704e9fe3064197aa" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "token_lock_status" ADD CONSTRAINT "FK_0b8f6070087f612d406fa89f636" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "token_lock_status" ADD CONSTRAINT "FK_a82baa649c6a106345fe778cc5e" FOREIGN KEY ("guardianId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "token_ledger_entries" ADD CONSTRAINT "FK_3ee53a641db6c32b4bc1fdc5329" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_entitlements" ADD CONSTRAINT "FK_32be92753914c65059636eee589" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sponsors" ADD CONSTRAINT "FK_f8008e60922b182bd3de4d2ab4c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sponsorships" ADD CONSTRAINT "FK_11300c2ba3817ba2c81eba0b8cc" FOREIGN KEY ("sponsorId") REFERENCES "sponsors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sponsorships" ADD CONSTRAINT "FK_53f610930641bd475788c9cecef" FOREIGN KEY ("beneficiaryId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sponsorships" ADD CONSTRAINT "FK_d2a2f60c3cbdac98194ff5ca325" FOREIGN KEY ("goalId") REFERENCES "goals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sponsorship_ledger_entries" ADD CONSTRAINT "FK_571c0ebc4d4f6034b911a96c773" FOREIGN KEY ("sponsorId") REFERENCES "sponsors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sponsorship_ledger_entries" ADD CONSTRAINT "FK_2c361d81b3f1bd0bb32896c6e55" FOREIGN KEY ("beneficiaryId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recommendations" ADD CONSTRAINT "FK_fe2bbafb624389915b622d33041" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_e747534006c6e3c2f09939da60f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_90016cade5e88271727a89f0a26" FOREIGN KEY ("recommendationId") REFERENCES "recommendations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consent_records" ADD CONSTRAINT "FK_325a36bd104daa11a3d4542afa9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consent_records" ADD CONSTRAINT "FK_8a395f121da64b0859693225894" FOREIGN KEY ("guardianId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "consent_records" DROP CONSTRAINT "FK_8a395f121da64b0859693225894"`);
        await queryRunner.query(`ALTER TABLE "consent_records" DROP CONSTRAINT "FK_325a36bd104daa11a3d4542afa9"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_90016cade5e88271727a89f0a26"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_e747534006c6e3c2f09939da60f"`);
        await queryRunner.query(`ALTER TABLE "recommendations" DROP CONSTRAINT "FK_fe2bbafb624389915b622d33041"`);
        await queryRunner.query(`ALTER TABLE "sponsorship_ledger_entries" DROP CONSTRAINT "FK_2c361d81b3f1bd0bb32896c6e55"`);
        await queryRunner.query(`ALTER TABLE "sponsorship_ledger_entries" DROP CONSTRAINT "FK_571c0ebc4d4f6034b911a96c773"`);
        await queryRunner.query(`ALTER TABLE "sponsorships" DROP CONSTRAINT "FK_d2a2f60c3cbdac98194ff5ca325"`);
        await queryRunner.query(`ALTER TABLE "sponsorships" DROP CONSTRAINT "FK_53f610930641bd475788c9cecef"`);
        await queryRunner.query(`ALTER TABLE "sponsorships" DROP CONSTRAINT "FK_11300c2ba3817ba2c81eba0b8cc"`);
        await queryRunner.query(`ALTER TABLE "sponsors" DROP CONSTRAINT "FK_f8008e60922b182bd3de4d2ab4c"`);
        await queryRunner.query(`ALTER TABLE "subscription_entitlements" DROP CONSTRAINT "FK_32be92753914c65059636eee589"`);
        await queryRunner.query(`ALTER TABLE "token_ledger_entries" DROP CONSTRAINT "FK_3ee53a641db6c32b4bc1fdc5329"`);
        await queryRunner.query(`ALTER TABLE "token_lock_status" DROP CONSTRAINT "FK_a82baa649c6a106345fe778cc5e"`);
        await queryRunner.query(`ALTER TABLE "token_lock_status" DROP CONSTRAINT "FK_0b8f6070087f612d406fa89f636"`);
        await queryRunner.query(`ALTER TABLE "token_balances" DROP CONSTRAINT "FK_a9f4195c452704e9fe3064197aa"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "FK_45db60741e56aa6941b7cf77fde"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "FK_57dd8a3fc26eb760d076bf8840e"`);
        await queryRunner.query(`ALTER TABLE "roadmaps" DROP CONSTRAINT "FK_4ecf772a639c37f4b05b8a07cbb"`);
        await queryRunner.query(`ALTER TABLE "roadmaps" DROP CONSTRAINT "FK_29f718c5a5cb41f2266d21ba207"`);
        await queryRunner.query(`ALTER TABLE "milestones" DROP CONSTRAINT "FK_17e022d167f4860adfaf3332326"`);
        await queryRunner.query(`ALTER TABLE "resources" DROP CONSTRAINT "FK_a9bd86651b6a4e30c5e2e9f235c"`);
        await queryRunner.query(`ALTER TABLE "connectors" DROP CONSTRAINT "FK_d9f4add3509272c1aec440c3d45"`);
        await queryRunner.query(`ALTER TABLE "interest_signals" DROP CONSTRAINT "FK_3b90bf0281c016550b1b0ad518f"`);
        await queryRunner.query(`ALTER TABLE "interest_signals" DROP CONSTRAINT "FK_ab1b51d46b9d2bd40ce08ee876f"`);
        await queryRunner.query(`ALTER TABLE "guardianship_links" DROP CONSTRAINT "FK_2e689397cdda619d53734a94853"`);
        await queryRunner.query(`ALTER TABLE "guardianship_links" DROP CONSTRAINT "FK_1f6276d2420789d3800d8cde347"`);
        await queryRunner.query(`ALTER TABLE "user_profiles" DROP CONSTRAINT "FK_8481388d6325e752cd4d7e26c6d"`);
        await queryRunner.query(`DROP TABLE "consent_records"`);
        await queryRunner.query(`DROP TABLE "favorites"`);
        await queryRunner.query(`DROP TABLE "recommendations"`);
        await queryRunner.query(`DROP TYPE "public"."recommendations_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recommendations_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recommendations_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recommendations_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05b878bab57cd765e539ec5982"`);
        await queryRunner.query(`DROP TABLE "sponsorship_ledger_entries"`);
        await queryRunner.query(`DROP TYPE "public"."sponsorship_ledger_entries_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sponsorship_ledger_entries_type_enum"`);
        await queryRunner.query(`DROP TABLE "sponsorships"`);
        await queryRunner.query(`DROP TYPE "public"."sponsorships_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sponsorships_type_enum"`);
        await queryRunner.query(`DROP TABLE "sponsors"`);
        await queryRunner.query(`DROP TYPE "public"."sponsors_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sponsors_type_enum"`);
        await queryRunner.query(`DROP TABLE "subscription_entitlements"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_entitlements_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed128f7dc3b032587678927664"`);
        await queryRunner.query(`DROP TABLE "token_ledger_entries"`);
        await queryRunner.query(`DROP TYPE "public"."token_ledger_entries_referencetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."token_ledger_entries_type_enum"`);
        await queryRunner.query(`DROP TABLE "token_lock_status"`);
        await queryRunner.query(`DROP TYPE "public"."token_lock_status_lockreason_enum"`);
        await queryRunner.query(`DROP TABLE "token_settings"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "token_balances"`);
        await queryRunner.query(`DROP TABLE "goals"`);
        await queryRunner.query(`DROP TYPE "public"."goals_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."goals_category_enum"`);
        await queryRunner.query(`DROP TABLE "roadmaps"`);
        await queryRunner.query(`DROP TYPE "public"."roadmaps_status_enum"`);
        await queryRunner.query(`DROP TABLE "milestones"`);
        await queryRunner.query(`DROP TYPE "public"."milestones_verificationmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."milestones_status_enum"`);
        await queryRunner.query(`DROP TABLE "resources"`);
        await queryRunner.query(`DROP TYPE "public"."resources_type_enum"`);
        await queryRunner.query(`DROP TABLE "connectors"`);
        await queryRunner.query(`DROP TYPE "public"."connectors_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."connectors_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2e053d53aafa4ea01c929b1c3"`);
        await queryRunner.query(`DROP TABLE "interest_signals"`);
        await queryRunner.query(`DROP TYPE "public"."interest_signals_entitytype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."interest_signals_source_enum"`);
        await queryRunner.query(`DROP TABLE "guardianship_links"`);
        await queryRunner.query(`DROP TYPE "public"."guardianship_links_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."guardianship_links_relationship_enum"`);
        await queryRunner.query(`DROP TABLE "user_profiles"`);
    }

}
